### PR TITLE
improv!: make format tags a hashmap

### PR DESCRIPTION
**Pull request by imLinguin**
Use `std::collections::HashMap` instead of custom struct.

This allows to check for tags specific to file types.  
For example for `mp3` file format: `title` `album` `artist`   
thus not limiting the functionality of the library

### CODE REVIEW

**Comment by theduke** [comment]
There is a better solution that doesn't lose the well-known fields.

We can capture all additional fields not specified in the struct with ` #[serde(flatten)]`.

```rust
    #[serde(flatten)]
    pub extra: HashMap<String, serde_json::Value>`
```

**Comment by theduke** [comment]
Could you update the PR to use that approach?

**Comment by imLinguin** [comment]
Sure, gonna do that as soon as possible

**Comment by theduke** [comment]
Thanks.

PS: also feel free to add additional fields you want/need to the struct so they are available in a type-safe manner.

**Pull request merged**
