### PR TITLE
Use Options for Stream.start_pts, Stream.start_time, Format.duration, Format.bit_rate

### PR DESCRIPTION
**Pull request by MCOfficer**
This PR wraps a few values in Options, since i found them to be missing on one of my files. The file itself is fairly standard, having been produced by Mkvmerge, so ffprobe-rs shouldn't error out due to missing values.

### CODE REVIEW

**Comment by theduke** [comment]
Thanks!

**Comment by theduke** [comment]
ps: If you have a test file, it would be great to have one in the repo. (see `/tests`)

**Comment by MCOfficer** [comment]
> ps: If you have a test file, it would be great to have one in the repo. (see `/tests`)

Can't share that specific file, but i'll see if i can cook up a sample. Even if i can't, I'm regularly scanning my entire library with this crate, so I have a bit of a smoke test going ;)

**Comment by MCOfficer** [comment]
Another thought, would it be ok if i just gave you the ffprobe output as json? That's still enough to test the deserializer.

**Pull request merged**
